title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://42crmo4.github.io

aux_links:
  Repository: https://github.com/42CrMo4/gll.wf

include:
  - index.md
  - standards

plugins:
  - jekyll-redirect-from
