title: GLL.wf
description: Dedicated Standards and Onformation for Electronics and Microcontrollers.
theme: just-the-docs

url: https://42crmo4.github.io

aux_links:
  Repository: https://github.com/42CrMo4/gll.wf

include:
  - index.md
  - standards

plugins:
  - jekyll-redirect-from
